name: Spotless check

on:
  push:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened ]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'corretto'
      - name: Run Spotless check - if ❌ run .\gradlew spotlessJavaApply
        run: ./gradlew spotlessJavaCheck